env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      cpu: 8
      memory: 20G
      
  Check_script: 
   - bash -c "$(curl -sL https://raw.githubusercontent.com/Sanju0910/PitchBlack-CI/main/build.sh)"
